# Generated by Django 3.1.3 on 2020-11-16 02:17

from django.db import migrations, models
import uuid

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('result', models.JSONField(null=True)),
                ('result_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(max_length=50)),
                ('timeout', models.PositiveIntegerField(null=True)),                
                ('type', models.TextField()),
            ],
            options={
                'db_table': 'Todos',
            },
        ),
    ]
